### ISSUE TITLE
will not inject

### ISSUE THREAD

**Issue by xxmrdark3xx** [Godsoft029/Horion#55]
ay yall i need some assistance, my horion doesnt inject it used to work, i did the following; get c++reinstalled, reinstalled horion and minecraft, tried to use horion in dev mode, used cheat engine to inject it said injection failed. i also tried one version of extreme injector and it didnt detect minecraft, and i tried extreme injector v3 it detected minecraft but gave me this error; https://image.prntscr.com/image/EUWIvlq2SUith7LWUoGyGg.png
i also did all of the above in admin and made sure it has full control.

**Comment by KoKoDaHoE** [comment]
Have you tried getting a better computer (x64)

**Comment by xxmrdark3xx** [comment]
its x64 already

**Comment by xxmrdark3xx** [comment]
did i mention it used to work? it happened over night

**Comment by Godsoft029** [comment]
thats pretty suss dude, need more info

**Comment by xxmrdark3xx** [comment]
well what happened was it was working fine for coupel of weeks then one time i did a scan on malwarebytes and suddenly the app  stopped working, i dont know if its the cause or not thts the only thing different idk what type of information do you need cause i really dont know how this happened myself, if i did id of worked it out

**Comment by xxmrdark3xx** [comment]
> thats pretty suss dude, need more info

well what happened was it was working fine for coupel of weeks then one time i did a scan on malwarebytes and suddenly the app  stopped working, i dont know if its the cause or not thts the only thing different idk what type of information do you need cause i really dont know how this happened myself, if i did id of worked it out @Godsoft029

**Comment by xxmrdark3xx** [comment]
i have also white listed the folder that contains my dll, and the injectors and i disabled my anti viruses still wont work

**Comment by xxmrdark3xx** [comment]
http://prntscr.com/ozfswb what i get when i inject through xenos

**Comment by Godsoft029** [comment]
yea idk

**Comment by xxmrdark3xx** [comment]
F

**Comment by EndmyExistence** [comment]
have you bothered to look up the error code @xxmrdark3xx
